### PR TITLE
[CULT-136] docker-compose for dev

### PR DESCRIPTION
**Pull request by ghost**
* Adds `docker-compose.yaml` for local development.

Setup:

```bash
echo "127.0.0.1       dex dex-signin" | sudo tee -a /etc/hosts
```

Usage:

```bash
docker-compose start
open http://dex:5556
```

### CODE REVIEW

**Comment by jramos** [comment]
Note: I've pushed an updated image to ECR tagged as `v2.9.0`.

**Comment by ghost** [comment]
Note: I've pushed updated Docker images to ECR, tagged as `v2.9.0`.

**Comment by feynmanliang** [comment]
```
 ---> fc030125d929
Step 9/15 : COPY _output/static/* /static/
ERROR: Service 'dex-signin' failed to build: COPY failed: no source files were specified
```

This is because there's  some required steps in the Makefile not present in the Docker build (hence `docker-compose build` will fail)

**Comment by feynmanliang** [comment]
The build artifacts all use `coreos/dex` but this repo is `liquidlabs-co/dex`. This isn't a problem in the docker container since we move this to `$GOROOT/.../coreos/dex` but it prohibits building outside the container

**Comment by feynmanliang** [comment]
What's the expected behavior in browser? 

image


To repro:
1. `go get github.com/liquidlabs-co/dex` and checkout your branch
1. `make docker-image-example-app`
1. `docker-compose up`
1. `open localhost:5556`

**Comment by ghost** [comment]
@feynmanliang -- I fixed the `_output` build issue.

Port `5556` is dex. You need to open http://dex-signin:5555/ for the landing page.

**Comment by feynmanliang** [comment]
WOMM

**Pull request merged**
